<a href="https://colab.research.google.com/github/kevinjmcmahon/CSCI5832_FinalProject/blob/main/CSI5832_hptune_grembert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SemEval Task 9 POLAR

### Subtask 3 - Manifestation Identification

### Hyper-parameter tune POC

By: Kevin Mcmahon, Caleb Kumar

Mount Google Drive to allow access to files stored in the user's Drive. This command will prompt the user for authorization.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Saving the Data Directory**

In [2]:
base_dir = '/content/drive/MyDrive/SemEval2026/'
data_dir = base_dir + 'data/subtask3/'

### Import statements

In [3]:
!pip install optuna
!pip install -U transformers

import pandas as pd

from sklearn.metrics import recall_score, precision_score, f1_score
import numpy as np
import random
import math

import torch

from sklearn.metrics import f1_score

from transformers import (
    AutoTokenizer,
    AutoConfig,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
    set_seed,
)
from torch.utils.data import Dataset
import wandb
from transformers import AutoConfig, AutoModelForSequenceClassification

import optuna
from optuna.samplers import TPESampler

import gc

Collecting optuna
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.2)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 28.5 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Collecting transformers
  Downloading transformers-4.57.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.11.12)
Downloading transformers-4.57.3-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 150.4 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.1
    Uninstalling transformers-4.57.1:
      Successfully uninstalled transformers-4.57.1
Successfully installed transformers-4.57.3

### Importing / Formatting Data

In [4]:
base_dir = '/content/drive/MyDrive/SemEval2026/'
data_dir = base_dir + 'data/subtask3/'

from sklearn.model_selection import train_test_split

languages = ["eng","arb","deu"]

train_dfs = {}
dev_dfs = {}

for lang in languages:
    train_dfs[lang] = pd.read_csv(data_dir + f"train/{lang}.csv")
    train_dfs[lang]["language"] = lang
    dev_dfs[lang] = pd.read_csv(data_dir + f"dev/{lang}.csv")
    dev_dfs[lang]["language"] = lang

train_full = pd.concat([train_dfs[lang] for lang in languages], ignore_index=True)
dev_full = pd.concat([dev_dfs[lang] for lang in languages], ignore_index=True)

# 80/20 split for train/validation, preserving language distribution
train, validation = train_test_split(
    train_full,
    test_size=0.2,
    random_state=42,
    stratify=train_full["language"]
)

### Defining Dataset Object

In [5]:
# Dataset class (already multi-label friendly)
class PolarizationDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding=False,
            max_length=self.max_length,
            return_tensors='pt'
        )

        item = {key: encoding[key].squeeze() for key in encoding.keys()}
        # multi-label → float labels
        item['labels'] = torch.tensor(label, dtype=torch.float)
        return item

### Defining Evaluation Metric

In [6]:
from sklearn.metrics import f1_score, accuracy_score

def compute_metrics_multilabel(p):
    # p.predictions is a numpy array of logits: (num_examples, num_labels)
    logits = torch.tensor(p.predictions)
    probs = torch.sigmoid(logits).numpy()

    # Try a slightly lower threshold to avoid "all zeros" early on.
    # You can tune this later; 0.3–0.4 is often more sensible for imbalanced multilabel.
    threshold = 0.3
    preds = (probs >= threshold).astype(int)

    labels = p.label_ids

    f1_macro = f1_score(labels, preds, average="macro", zero_division=0)
    # This is *subset* accuracy (exact match over all 6 labels for each example)
    accuracy = accuracy_score(labels, preds)

    return {
        "f1_macro": f1_macro,
        "accuracy": accuracy,
    }

In [7]:
MODEL_NAME = "google/rembert"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

MAX_LEN = 128

label_cols = [
    "vilification",
    "extreme_language",
    "stereotype",
    "invalidation",
    "lack_of_empathy",
    "dehumanization",
]

train_dataset = PolarizationDataset(
    train["text"].tolist(),
    train[label_cols].values.tolist(),
    tokenizer,
    max_length=MAX_LEN,
)

val_dataset = PolarizationDataset(
    validation["text"].tolist(),
    validation[label_cols].values.tolist(),
    tokenizer,
    max_length=MAX_LEN,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/263 [00:00<?, ?B/s]

sentencepiece.model:   0%|          | 0.00/4.70M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

### Defining Callback Metrics

This will allow us to evalaute the performance of the experiment so that we can make sure that the model is learning.

In [8]:
from transformers import TrainerCallback

class EpochMetricsCallback(TrainerCallback):
    def __init__(self, trainer, train_dataset, val_dataset, trial=None):
        super().__init__()
        self.trainer = trainer
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.trial = trial
        self.best_val_f1 = 0.0

    def on_epoch_end(self, args, state, control, **kwargs):
        epoch = state.epoch
        epoch_str = f"{epoch:.0f}" if epoch is not None and not math.isnan(epoch) else "?"

        print(f"\n===== Epoch {epoch_str} =====")

        # ---- Train metrics ----
        train_metrics = self.trainer.evaluate(eval_dataset=self.train_dataset)
        train_loss = train_metrics.get("eval_loss", float("nan"))
        train_f1 = train_metrics.get("eval_f1_macro", float("nan"))
        train_acc = train_metrics.get("eval_accuracy", float("nan"))
        print(
            "Train - "
            f"loss={train_loss:.4f}, "
            f"F1={train_f1:.4f}, "
            f"Acc={train_acc:.4f}"
        )

        # ---- Validation metrics ----
        val_metrics = self.trainer.evaluate(eval_dataset=self.val_dataset)
        val_loss = val_metrics.get("eval_loss", float("nan"))
        val_f1 = val_metrics.get("eval_f1_macro", 0.0)
        val_acc = val_metrics.get("eval_accuracy", float("nan"))
        print(
            "Val   - "
            f"loss={val_loss:.4f}, "
            f"F1={val_f1:.4f}, "
            f"Acc={val_acc:.4f}"
        )
        print("=========================\n")

        # Track best validation F1 for this trial
        if val_f1 > self.best_val_f1:
            self.best_val_f1 = val_f1

        # Report to Optuna + pruning
        if self.trial is not None:
            step = int(epoch) if epoch is not None and not math.isnan(epoch) else state.global_step
            self.trial.report(val_f1, step=step)
            if self.trial.should_prune():
                print(f"Pruning trial at epoch {epoch_str} with val F1={val_f1:.4f}")
                raise optuna.exceptions.TrialPruned()

### Optuna Objective

Optuna is a hyper-parameter tuning framework used to automate the process of hyper-parameter tuning while also doing it in a more efficient way using math rather than guess & check. I have previously used this in my final project for Deep Learning. The objective sets which parameters should be tuned, what the bounds for tuning the parameters are and what is the goal of the "sudy" - max Macro F1 in our case. Optuna will automatically suggest new parameters to test given the perfromance of the previously tested parameters. It will keep trying new "trials" for as long as you set unless it hits a time limit that you set... important when working in Google Colab.

In [9]:
import optuna
import gc
import torch
from transformers import TrainingArguments, Trainer
from transformers import DataCollatorWithPadding

def build_model(dropout: float):
    config = AutoConfig.from_pretrained(
        MODEL_NAME,
        num_labels=len(label_cols),
        problem_type="multi_label_classification",
        hidden_dropout_prob=dropout,
        attention_probs_dropout_prob=dropout,
    )
    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        config=config,
    )
    return model

GLOBAL_SEED = 42  # pick any int you like and stick with it


def seed_everything(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    # HuggingFace helper (sets some internal RNGs)
    set_seed(seed)


# assumes:
# - GLOBAL_SEED is defined (e.g., GLOBAL_SEED = 42)
# - seed_everything(seed: int) is defined
# - build_model(dropout: float) is defined
# - compute_metrics_multilabel is defined
# - train_dataset, val_dataset, tokenizer, MODEL_NAME, label_cols are defined


def objective(trial: optuna.trial.Trial) -> float:
    trial_seed = GLOBAL_SEED + trial.number
    seed_everything(trial_seed)

    # Narrow LR around ~1e-5
    learning_rate = trial.suggest_float(
        "learning_rate",
        5e-6,    # lower
        2e-5,    # upper
        log=True,
    )

    # You’ve seen good behavior by 4–8 epochs
    num_train_epochs = trial.suggest_int("num_train_epochs", 4, 8)

    # If VRAM is fine, you can even fix this to 16
    per_device_train_batch_size = trial.suggest_categorical(
        "per_device_train_batch_size",
        [16],
    )

    # WD around 0.066
    weight_decay = trial.suggest_float("weight_decay", 0.03, 0.08)

    # Warmup around 0.05
    warmup_ratio = trial.suggest_float("warmup_ratio", 0.02, 0.08)

    # Dropout around 0.15
    dropout = trial.suggest_float("dropout", 0.12, 0.22)

    model = build_model(dropout)
    training_args = TrainingArguments(
        output_dir="./subtask3_tmp",
        num_train_epochs=num_train_epochs,
        learning_rate=learning_rate,
        per_device_train_batch_size=per_device_train_batch_size,
        per_device_eval_batch_size=per_device_train_batch_size,
        save_strategy="no",
        logging_steps=600,
        report_to="none",
        weight_decay=weight_decay,
        warmup_ratio=warmup_ratio,
        metric_for_best_model="f1_macro",
        load_best_model_at_end=False,
        fp16=torch.cuda.is_available(),
        seed=trial_seed,
        data_seed=trial_seed,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=compute_metrics_multilabel,
        data_collator=DataCollatorWithPadding(tokenizer),
    )

    epoch_cb = EpochMetricsCallback(
        trainer=trainer,
        train_dataset=train_dataset,
        val_dataset=val_dataset,
        trial=trial,
    )
    trainer.add_callback(epoch_cb)

    print("Trainer device:", trainer.args.device)

    try:
        trainer.train()
        eval_results = trainer.evaluate()
        print("Final eval metrics:", eval_results)
        f1 = max(epoch_cb.best_val_f1, eval_results["eval_f1_macro"])
    finally:
        del trainer, model
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    return f1

### Run Optuna "Study"

Above we defined the study, here we are actually going to run it.

In [10]:
study_name = f"study_{MODEL_NAME}"

sampler = TPESampler(seed=GLOBAL_SEED)

study = optuna.create_study(
    direction="maximize",
    study_name=study_name,
    sampler=sampler,
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=1),
)

print(f"Starting study '{study_name}' with a 4-hour timeout...")
study.optimize(objective, n_trials=20, timeout=14400)

print("Best F1:", study.best_value)
print("Best params:", study.best_trial.params)

[I 2025-11-25 17:55:31,694] A new study created in memory with name: study_google/rembert

Starting study 'study_google/rembert' with a 4-hour timeout...

config.json:   0%|          | 0.00/686 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.30G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.30G [00:00<?, ?B/s]

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5315, F1=0.0779, Acc=0.0123
Val   - loss=0.5137, F1=0.0752, Acc=0.0124
=========================


===== Epoch 2 =====
Train - loss=0.5222, F1=0.2277, Acc=0.0390
Val   - loss=0.5081, F1=0.2200, Acc=0.0400
=========================


===== Epoch 3 =====
Train - loss=0.5238, F1=0.1583, Acc=0.0261
Val   - loss=0.5081, F1=0.1541, Acc=0.0271
=========================


===== Epoch 4 =====
Train - loss=0.5205, F1=0.1583, Acc=0.0261
Val   - loss=0.5065, F1=0.1541, Acc=0.0271
=========================


===== Epoch 5 =====
Train - loss=0.5200, F1=0.0821, Acc=0.0162
Val   - loss=0.5054, F1=0.0795, Acc=0.0103
=========================


===== Epoch 6 =====
Train - loss=0.5204, F1=0.1583, Acc=0.0261
Val   - loss=0.5065, F1=0.1541, Acc=0.0271
=========================


===== Epoch 7 =====
Train - loss=0.5203, F1=0.0824, Acc=0.0162
Val   - loss=0.5047, F1=0.0801, Acc=0.0103
=========================


===== Epoch 8 =====
Train - loss=0.5203, F1=0.0822, Acc=0.0162
Val   - loss=0.5046, F1=0.0795, Acc=0.0103
=========================

[I 2025-11-25 18:17:23,612] Trial 0 finished with value: 0.21999668099108363 and parameters: {'learning_rate': 8.403604888695184e-06, 'num_train_epochs': 8, 'per_device_train_batch_size': 16, 'weight_decay': 0.06659969709057026, 'warmup_ratio': 0.05591950905182219, 'dropout': 0.13560186404424365}. Best is trial 0 with value: 0.21999668099108363.

Final eval metrics: {'eval_loss': 0.5045797228813171, 'eval_f1_macro': 0.07952204367531933, 'eval_accuracy': 0.010281385281385282, 'eval_runtime': 6.6138, 'eval_samples_per_second': 279.417, 'eval_steps_per_second': 17.539, 'epoch': 8.0}

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5323, F1=0.2092, Acc=0.0265
Val   - loss=0.5210, F1=0.2043, Acc=0.0341
=========================


===== Epoch 2 =====
Train - loss=0.5245, F1=0.1583, Acc=0.0260
Val   - loss=0.5103, F1=0.1543, Acc=0.0271
=========================


===== Epoch 3 =====
Train - loss=0.5287, F1=0.1583, Acc=0.0261
Val   - loss=0.5153, F1=0.1541, Acc=0.0271
=========================


===== Epoch 4 =====
Train - loss=0.5259, F1=0.1585, Acc=0.0261
Val   - loss=0.5124, F1=0.1541, Acc=0.0271
=========================

[I 2025-11-25 18:28:20,425] Trial 1 finished with value: 0.20426777776827107 and parameters: {'learning_rate': 6.207090305742937e-06, 'num_train_epochs': 4, 'per_device_train_batch_size': 16, 'weight_decay': 0.07330880728874675, 'warmup_ratio': 0.056066900704592526, 'dropout': 0.19080725777960456}. Best is trial 0 with value: 0.21999668099108363.

Final eval metrics: {'eval_loss': 0.5123615264892578, 'eval_f1_macro': 0.1541405513051667, 'eval_accuracy': 0.027056277056277056, 'eval_runtime': 6.6556, 'eval_samples_per_second': 277.662, 'eval_steps_per_second': 17.429, 'epoch': 4.0}

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5296, F1=0.2549, Acc=0.0352
Val   - loss=0.5178, F1=0.2486, Acc=0.0335
=========================


===== Epoch 2 =====
Train - loss=0.5238, F1=0.2253, Acc=0.0287
Val   - loss=0.5112, F1=0.2176, Acc=0.0287
=========================


===== Epoch 3 =====
Train - loss=0.5213, F1=0.2294, Acc=0.0424
Val   - loss=0.5085, F1=0.2232, Acc=0.0433
=========================


===== Epoch 4 =====
Train - loss=0.5283, F1=0.2296, Acc=0.0411
Val   - loss=0.5174, F1=0.2210, Acc=0.0427
=========================


===== Epoch 5 =====
Train - loss=0.5195, F1=0.2273, Acc=0.0600
Val   - loss=0.5050, F1=0.2236, Acc=0.0693
=========================


===== Epoch 6 =====
Train - loss=0.5165, F1=0.2406, Acc=0.0799
Val   - loss=0.5022, F1=0.2378, Acc=0.0844
=========================


===== Epoch 7 =====
Train - loss=0.5096, F1=0.2632, Acc=0.1023
Val   - loss=0.4949, F1=0.2595, Acc=0.1098
=========================


===== Epoch 8 =====
Train - loss=0.5071, F1=0.2631, Acc=0.1294
Val   - loss=0.4918, F1=0.2557, Acc=0.1461
=========================

[I 2025-11-25 18:49:58,340] Trial 2 finished with value: 0.25954834198076443 and parameters: {'learning_rate': 5.144736127521127e-06, 'num_train_epochs': 8, 'per_device_train_batch_size': 16, 'weight_decay': 0.07162213204002109, 'warmup_ratio': 0.03274034664069657, 'dropout': 0.13818249672071006}. Best is trial 2 with value: 0.25954834198076443.

Final eval metrics: {'eval_loss': 0.4918343126773834, 'eval_f1_macro': 0.2556743370221687, 'eval_accuracy': 0.1461038961038961, 'eval_runtime': 6.6489, 'eval_samples_per_second': 277.941, 'eval_steps_per_second': 17.447, 'epoch': 8.0}

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5286, F1=0.2034, Acc=0.0261
Val   - loss=0.5151, F1=0.1983, Acc=0.0249
=========================


===== Epoch 2 =====
Train - loss=0.5224, F1=0.1535, Acc=0.1429
Val   - loss=0.5065, F1=0.1509, Acc=0.1558
=========================


===== Epoch 3 =====
Train - loss=0.5207, F1=0.1609, Acc=0.1695
Val   - loss=0.5044, F1=0.1587, Acc=0.1764
=========================


===== Epoch 4 =====
Train - loss=0.5234, F1=0.1097, Acc=0.2264
Val   - loss=0.5061, F1=0.1059, Acc=0.2256
=========================


===== Epoch 5 =====
Train - loss=0.5231, F1=0.1060, Acc=0.2152
Val   - loss=0.5058, F1=0.1039, Acc=0.2202
=========================

[I 2025-11-25 19:03:32,820] Trial 3 finished with value: 0.19825014086930173 and parameters: {'learning_rate': 6.4474876947936455e-06, 'num_train_epochs': 5, 'per_device_train_batch_size': 16, 'weight_decay': 0.05623782158161189, 'warmup_ratio': 0.04591670111852694, 'dropout': 0.14912291401980418}. Best is trial 2 with value: 0.25954834198076443.

Final eval metrics: {'eval_loss': 0.5058370232582092, 'eval_f1_macro': 0.10386353130656477, 'eval_accuracy': 0.22023809523809523, 'eval_runtime': 6.661, 'eval_samples_per_second': 277.438, 'eval_steps_per_second': 17.415, 'epoch': 5.0}

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5247, F1=0.0044, Acc=0.5463
Val   - loss=0.5079, F1=0.0029, Acc=0.5617
=========================


===== Epoch 2 =====
Train - loss=0.5215, F1=0.1583, Acc=0.0261
Val   - loss=0.5078, F1=0.1549, Acc=0.0271
=========================


===== Epoch 3 =====
Train - loss=0.5217, F1=0.0821, Acc=0.0162
Val   - loss=0.5058, F1=0.0801, Acc=0.0103
=========================


===== Epoch 4 =====
Train - loss=0.5201, F1=0.0821, Acc=0.0162
Val   - loss=0.5049, F1=0.0801, Acc=0.0103
=========================

[I 2025-11-25 19:14:25,057] Trial 4 finished with value: 0.15487154545721352 and parameters: {'learning_rate': 1.1677292338861152e-05, 'num_train_epochs': 4, 'per_device_train_batch_size': 16, 'weight_decay': 0.04460723242676091, 'warmup_ratio': 0.0419817105976215, 'dropout': 0.1656069984217036}. Best is trial 2 with value: 0.25954834198076443.

Final eval metrics: {'eval_loss': 0.5048903226852417, 'eval_f1_macro': 0.08014277613962721, 'eval_accuracy': 0.010281385281385282, 'eval_runtime': 6.5704, 'eval_samples_per_second': 281.259, 'eval_steps_per_second': 17.655, 'epoch': 4.0}

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5224, F1=0.1583, Acc=0.0261

[I 2025-11-25 19:17:10,002] Trial 5 pruned.

Val   - loss=0.5083, F1=0.1541, Acc=0.0271
=========================

Pruning trial at epoch 1 with val F1=0.1541

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5226, F1=0.1489, Acc=0.2309

[I 2025-11-25 19:19:54,718] Trial 6 pruned.

Val   - loss=0.5063, F1=0.1465, Acc=0.2338
=========================

Pruning trial at epoch 1 with val F1=0.1465

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5244, F1=0.1583, Acc=0.0261

[I 2025-11-25 19:22:39,157] Trial 7 pruned.

Val   - loss=0.5114, F1=0.1541, Acc=0.0271
=========================

Pruning trial at epoch 1 with val F1=0.1541

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5195, F1=0.1514, Acc=0.0254

[I 2025-11-25 19:25:23,467] Trial 8 pruned.

Val   - loss=0.5059, F1=0.1461, Acc=0.0200
=========================

Pruning trial at epoch 1 with val F1=0.1461

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5277, F1=0.2277, Acc=0.0390
Val   - loss=0.5157, F1=0.2200, Acc=0.0400
=========================


===== Epoch 2 =====
Train - loss=0.5213, F1=0.0821, Acc=0.0162
Val   - loss=0.5071, F1=0.0795, Acc=0.0103
=========================


===== Epoch 3 =====
Train - loss=0.5206, F1=0.0821, Acc=0.0162
Val   - loss=0.5069, F1=0.0795, Acc=0.0103
=========================


===== Epoch 4 =====
Train - loss=0.5200, F1=0.0821, Acc=0.0162
Val   - loss=0.5053, F1=0.0795, Acc=0.0103
=========================


===== Epoch 5 =====
Train - loss=0.5199, F1=0.0821, Acc=0.0162
Val   - loss=0.5048, F1=0.0795, Acc=0.0103
=========================

[I 2025-11-25 19:38:56,375] Trial 9 finished with value: 0.21999668099108363 and parameters: {'learning_rate': 1.2527031373763456e-05, 'num_train_epochs': 5, 'per_device_train_batch_size': 16, 'weight_decay': 0.05600340105889054, 'warmup_ratio': 0.05280261676059678, 'dropout': 0.1384854455525527}. Best is trial 2 with value: 0.25954834198076443.

Final eval metrics: {'eval_loss': 0.5047722458839417, 'eval_f1_macro': 0.07952204367531933, 'eval_accuracy': 0.010281385281385282, 'eval_runtime': 6.6054, 'eval_samples_per_second': 279.77, 'eval_steps_per_second': 17.561, 'epoch': 5.0}

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5454, F1=0.2277, Acc=0.0390
Val   - loss=0.5343, F1=0.2200, Acc=0.0400
=========================


===== Epoch 2 =====
Train - loss=0.5207, F1=0.1583, Acc=0.0261
Val   - loss=0.5063, F1=0.1541, Acc=0.0271
=========================


===== Epoch 3 =====
Train - loss=0.5203, F1=0.1583, Acc=0.0261
Val   - loss=0.5054, F1=0.1541, Acc=0.0271
=========================


===== Epoch 4 =====
Train - loss=0.5202, F1=0.0821, Acc=0.0162
Val   - loss=0.5054, F1=0.0795, Acc=0.0103
=========================


===== Epoch 5 =====
Train - loss=0.5206, F1=0.0821, Acc=0.0162
Val   - loss=0.5054, F1=0.0795, Acc=0.0103
=========================


===== Epoch 6 =====
Train - loss=0.5204, F1=0.0821, Acc=0.0162
Val   - loss=0.5054, F1=0.0795, Acc=0.0103
=========================


===== Epoch 7 =====
Train - loss=0.5205, F1=0.0821, Acc=0.0162
Val   - loss=0.5048, F1=0.0795, Acc=0.0103
=========================


===== Epoch 8 =====
Train - loss=0.5202, F1=0.0821, Acc=0.0162
Val   - loss=0.5050, F1=0.0795, Acc=0.0103
=========================

[I 2025-11-25 20:00:25,402] Trial 10 finished with value: 0.21999668099108363 and parameters: {'learning_rate': 8.538807021905713e-06, 'num_train_epochs': 8, 'per_device_train_batch_size': 16, 'weight_decay': 0.07847685553939329, 'warmup_ratio': 0.021776325021421773, 'dropout': 0.18518665507781784}. Best is trial 2 with value: 0.25954834198076443.

Final eval metrics: {'eval_loss': 0.5049765706062317, 'eval_f1_macro': 0.07952204367531933, 'eval_accuracy': 0.010281385281385282, 'eval_runtime': 6.6287, 'eval_samples_per_second': 278.786, 'eval_steps_per_second': 17.5, 'epoch': 8.0}

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5224, F1=0.0000, Acc=0.5594
Val   - loss=0.5060, F1=0.0000, Acc=0.5828
=========================

Pruning trial at epoch 1 with val F1=0.0000

[I 2025-11-25 20:03:09,713] Trial 11 pruned.
Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5232, F1=0.1580, Acc=0.0259

[I 2025-11-25 20:05:53,988] Trial 12 pruned.

Val   - loss=0.5078, F1=0.1532, Acc=0.0249
=========================

Pruning trial at epoch 1 with val F1=0.1532

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5223, F1=0.1583, Acc=0.0261
Val   - loss=0.5071, F1=0.1541, Acc=0.0271
=========================

Pruning trial at epoch 1 with val F1=0.1541

[I 2025-11-25 20:08:37,373] Trial 13 pruned.
Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5233, F1=0.2289, Acc=0.0393
Val   - loss=0.5091, F1=0.2215, Acc=0.0406
=========================


===== Epoch 2 =====
Train - loss=0.5214, F1=0.0839, Acc=0.0466
Val   - loss=0.5050, F1=0.0816, Acc=0.0471
=========================


===== Epoch 3 =====
Train - loss=0.5231, F1=0.2289, Acc=0.0387
Val   - loss=0.5095, F1=0.2211, Acc=0.0406
=========================


===== Epoch 4 =====
Train - loss=0.5411, F1=0.2931, Acc=0.0323
Val   - loss=0.5314, F1=0.2859, Acc=0.0303
=========================


===== Epoch 5 =====
Train - loss=0.4849, F1=0.3452, Acc=0.2371
Val   - loss=0.4712, F1=0.3492, Acc=0.2565
=========================


===== Epoch 6 =====
Train - loss=0.4919, F1=0.3318, Acc=0.1695
Val   - loss=0.4807, F1=0.3281, Acc=0.1894
=========================


===== Epoch 7 =====
Train - loss=0.4880, F1=0.3770, Acc=0.1891
Val   - loss=0.4778, F1=0.3725, Acc=0.2094
=========================

[I 2025-11-25 20:27:27,985] Trial 14 finished with value: 0.3725024579903063 and parameters: {'learning_rate': 7.564375395874519e-06, 'num_train_epochs': 7, 'per_device_train_batch_size': 16, 'weight_decay': 0.07974258965850631, 'warmup_ratio': 0.025182135309156233, 'dropout': 0.13133376372667255}. Best is trial 14 with value: 0.3725024579903063.

Final eval metrics: {'eval_loss': 0.47776705026626587, 'eval_f1_macro': 0.3725024579903063, 'eval_accuracy': 0.20941558441558442, 'eval_runtime': 6.6338, 'eval_samples_per_second': 278.574, 'eval_steps_per_second': 17.486, 'epoch': 7.0}

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5242, F1=0.0000, Acc=0.5594

[I 2025-11-25 20:30:10,930] Trial 15 pruned.

Val   - loss=0.5069, F1=0.0000, Acc=0.5828
=========================

Pruning trial at epoch 1 with val F1=0.0000

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5159, F1=0.2217, Acc=0.1025
Val   - loss=0.5010, F1=0.2148, Acc=0.1039
=========================


===== Epoch 2 =====
Train - loss=0.5297, F1=0.1900, Acc=0.0283
Val   - loss=0.5167, F1=0.1879, Acc=0.0308
=========================


===== Epoch 3 =====
Train - loss=0.5241, F1=0.2080, Acc=0.0277
Val   - loss=0.5105, F1=0.2040, Acc=0.0271
=========================


===== Epoch 4 =====
Train - loss=0.5225, F1=0.2320, Acc=0.0374
Val   - loss=0.5085, F1=0.2270, Acc=0.0411
=========================


===== Epoch 5 =====
Train - loss=0.5256, F1=0.2307, Acc=0.0409
Val   - loss=0.5140, F1=0.2229, Acc=0.0449
=========================


===== Epoch 6 =====
Train - loss=0.5160, F1=0.2840, Acc=0.0964
Val   - loss=0.5048, F1=0.2757, Acc=0.1012
=========================


===== Epoch 7 =====
Train - loss=0.5041, F1=0.2656, Acc=0.1368
Val   - loss=0.4914, F1=0.2577, Acc=0.1418
=========================

[I 2025-11-25 20:49:01,898] Trial 16 finished with value: 0.27568797261828876 and parameters: {'learning_rate': 5.041925877219515e-06, 'num_train_epochs': 7, 'per_device_train_batch_size': 16, 'weight_decay': 0.07338181557748262, 'warmup_ratio': 0.03099659019262796, 'dropout': 0.12918929784195296}. Best is trial 14 with value: 0.3725024579903063.

Final eval metrics: {'eval_loss': 0.4914346933364868, 'eval_f1_macro': 0.25765704932953254, 'eval_accuracy': 0.14177489177489178, 'eval_runtime': 6.5608, 'eval_samples_per_second': 281.671, 'eval_steps_per_second': 17.681, 'epoch': 7.0}

Some weights of RemBertForSequenceClassification were not initialized from the model checkpoint at google/rembert and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Trainer device: cuda:0

===== Epoch 1 =====
Train - loss=0.5135, F1=0.2761, Acc=0.0394
Val   - loss=0.4975, F1=0.2760, Acc=0.0417
=========================

[W 2025-11-25 20:52:32,739] Trial 17 failed with parameters: {'learning_rate': 7.278162101972035e-06, 'num_train_epochs': 6, 'per_device_train_batch_size': 16, 'weight_decay': 0.07380799123199301, 'warmup_ratio': 0.028328770253155257, 'dropout': 0.12022517165419494} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/optuna/study/_optimize.py", line 205, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/tmp/ipython-input-1953625040.py", line 111, in objective
    trainer.train()
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 2325, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 2618, in _inner_training_loop
    batch_samples, num_items_in_batch = self.get_batch_samples(epoch_iterator, num_batches, args.device)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 5654, in get_batch_samples
    batch_samples.append(next(epoch_iterator))
                         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/accelerate/data_loader.py", line 577, in __iter__
    current_batch = send_to_device(current_batch, self.device, non_blocking=self._non_blocking)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/accelerate/utils/operations.py", line 154, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/tokenization_utils_base.py", line 839, in to
    k: v.to(device=device, non_blocking=non_blocking) if hasattr(v, "to") and callable(v.to) else v
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2025-11-25 20:52:32,742] Trial 17 failed with value None.

KeyboardInterrupt: